### PR TITLE
moved storage to /data, some cleanups, improved condition for APP_KEY…

### PR DESCRIPTION
**Pull request by sebarnd**
… generation

see InvoiceShelf/InvoiceShelf#17 5 for more info

### CODE REVIEW

**Comment by gdarko** [comment]
Hey @sebarnd  - I checked this and it looks very good. 

One thing, can you please revisit the VOLUME definition in the Dockerfile? I think this is out of date with those changes now. Do you think we can mount the whole /data directory  with a volume? 

Thanks.

**Comment by gdarko** [comment]
Hey @sebarnd 

I think something is wrong with the storage folder. We actually end up with nested "storage" directory.

```
root@37d64a703bc8:/var/www/html/InvoiceShelf# ls -la
total 1172
drwxr-xr-x 1 www-data www-data   4096 Feb 11 13:23 .
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 ..
-rw-r--r-- 1 www-data www-data    309 Feb 11 12:58 .editorconfig
lrwxrwxrwx 1 www-data www-data     10 Feb 11 13:23 .env -> /conf/.env
-rw-r--r-- 1 www-data www-data    681 Feb 11 12:58 .env.example
-rw-r--r-- 1 www-data www-data    318 Feb 11 12:58 .env.testing
-rw-r--r-- 1 www-data www-data    288 Feb 11 12:58 .eslintrc.mjs
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 .git
-rw-r--r-- 1 www-data www-data     61 Feb 11 12:58 .gitattributes
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 .github
-rw-r--r-- 1 www-data www-data    290 Feb 11 12:58 .gitignore
-rw-r--r-- 1 www-data www-data     60 Feb 11 12:58 .prettierrc.json
-rw-r--r-- 1 www-data www-data   5223 Feb 11 12:58 CODE_OF_CONDUCT.md
-rw-r--r-- 1 www-data www-data  34523 Feb 11 12:58 LICENSE
-rw-r--r-- 1 www-data www-data   2567 Feb 11 12:58 Makefile
-rw-r--r-- 1 www-data www-data    327 Feb 11 12:58 SECURITY.md
-rw-r--r-- 1 www-data www-data 379750 Feb 11 12:58 _ide_helper.php
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 app
-rwxr-xr-x 1 www-data www-data   1686 Feb 11 12:58 artisan
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 bootstrap
-rw-r--r-- 1 www-data www-data   2441 Feb 11 12:58 composer.json
-rw-r--r-- 1 www-data www-data 442540 Feb 11 12:58 composer.lock
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 config
-rw-r--r-- 1 www-data www-data    122 Feb 11 12:58 crowdin.yml
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 database
-rw-r--r-- 1 www-data www-data      4 Feb 11 12:58 docker_target
-rw-r--r-- 1 www-data www-data   1199 Feb 11 12:58 invoiceshelf.code-workspace
-rw-r--r-- 1 www-data www-data   1771 Feb 11 12:58 package.json
-rw-r--r-- 1 www-data www-data   1080 Feb 11 12:58 phpunit.xml
-rw-r--r-- 1 www-data www-data    103 Feb 11 12:58 postcss.config.cjs
drwxr-xr-x 1 www-data www-data   4096 Feb 11 13:01 public
-rw-r--r-- 1 www-data www-data   3302 Feb 11 12:58 readme.md
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 resources
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 routes
-rw-r--r-- 1 www-data www-data    541 Feb 11 12:58 server.php
lrwxrwxrwx 1 www-data www-data      5 Feb 11 13:23 storage -> /data
-rw-r--r-- 1 www-data www-data   3390 Feb 11 12:58 tailwind.config.js
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 tests
-rw-r--r-- 1 www-data www-data    563 Feb 11 12:58 tsconfig.json
drwxr-xr-x 1 www-data www-data   4096 Feb 11 12:58 vendor
-rw-r--r-- 1 www-data www-data     39 Feb 11 12:58 version.md
-rw-r--r-- 1 www-data www-data   1571 Feb 11 12:58 vite.config.js
-rw-r--r-- 1 www-data www-data 128985 Feb 11 12:58 yarn.lock
```
When i `ls` in the storage dir i get this, the "storage" dir is inside again.

```
root@37d64a703bc8:/var/www/html/InvoiceShelf# cd storage
root@37d64a703bc8:/var/www/html/InvoiceShelf/storage# ls -la
total 28
drwxrwsr-x 7 www-data www-data 4096 Feb 11 13:23 .
drwxr-xr-x 1 root     root     4096 Feb 11 13:23 ..
drwxrwsr-x 2 www-data www-data 4096 Feb 11 13:23 app
drwxrwsr-x 2 www-data www-data 4096 Feb 11 13:23 cache
drwxrwsr-x 5 www-data www-data 4096 Feb 11 13:23 framework
drwxrwsr-x 2 www-data www-data 4096 Feb 11 13:23 logs
drwxrwsr-x 6 www-data www-data 4096 Feb 11 13:23 storage
```
Thanks.

**Comment by sebarnd** [comment]
Oh yes, I'll commit the fix in a minute

**Comment by gdarko** [comment]
Thank you very much @sebarnd  - all good now.

**Pull request merged**
